lockfileIncludeTarballUrl: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  sharp: 0.34.4
#  vite: npm:rolldown-vite@7.1.20

publicHoistPattern:
  - nuxt-schema-org

resolutionMode: highest

savePrefix: ""
