lockfileIncludeTarballUrl: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver

publicHoistPattern:
  - "nuxt-schema-org"

resolutionMode: highest

savePrefix: ""
