lockfileIncludeTarballUrl: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  sharp: "0.34.4"
#   vite: "npm:rolldown-vite@latest"

publicHoistPattern:
  - "nuxt-schema-org"

resolutionMode: highest

savePrefix: ""
