lockfileIncludeTarballUrl: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver

patchedDependencies:
  '@mdit/plugin-alert@0.22.3': patches/@mdit__plugin-alert@0.22.3.patch
  '@mdit/plugin-align@0.22.2': patches/@mdit__plugin-align@0.22.2.patch
  '@mdit/plugin-footnote@0.22.3': patches/@mdit__plugin-footnote@0.22.3.patch
  '@mdit/plugin-img-lazyload@0.22.1': patches/@mdit__plugin-img-lazyload@0.22.1.patch
  '@mdit/plugin-img-size@0.22.3': patches/@mdit__plugin-img-size@0.22.3.patch
  '@mdit/plugin-ins@0.22.1': patches/@mdit__plugin-ins@0.22.1.patch
  '@mdit/plugin-katex@0.23.2': patches/@mdit__plugin-katex@0.23.2.patch
  '@mdit/plugin-mark@0.22.1': patches/@mdit__plugin-mark@0.22.1.patch
  '@mdit/plugin-spoiler@0.22.2': patches/@mdit__plugin-spoiler@0.22.2.patch
  '@mdit/plugin-tab@0.22.3': patches/@mdit__plugin-tab@0.22.3.patch
  '@mdit/plugin-tasklist@0.22.2': patches/@mdit__plugin-tasklist@0.22.2.patch
  '@mdit/plugin-tex@0.22.2': patches/@mdit__plugin-tex@0.22.2.patch
  '@types/markdown-it-attrs@4.1.3': patches/@types__markdown-it-attrs@4.1.3.patch
  '@types/markdown-it-emoji@3.0.1': patches/@types__markdown-it-emoji@3.0.1.patch
  '@types/markdown-it-link-attributes@3.0.5': patches/@types__markdown-it-link-attributes@3.0.5.patch
  assemblyscript@0.28.9: patches/assemblyscript@0.28.9.patch
  markdown-exit@1.0.0-beta.6: patches/markdown-exit@1.0.0-beta.6.patch
  markdown-it-anchor@9.2.0: patches/markdown-it-anchor@9.2.0.patch
  markdown-it-highlightjs@4.2.0: patches/markdown-it-highlightjs@4.2.0.patch
  markdown-it-toc-done-right@4.2.0: patches/markdown-it-toc-done-right@4.2.0.patch
  unplugin-vue-markdown@29.2.0: patches/unplugin-vue-markdown@29.2.0.patch

publicHoistPattern:
  - '@unhead/schema-org'

resolutionMode: highest

savePrefix: ''
