hoist: false

lockfileIncludeTarballUrl: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

resolutionMode: highest

savePrefix: ''

shamefullyHoist: true

virtualStoreDirMaxLength: 1024
