lockfileIncludeTarballUrl: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  vite: "~7.0.6"
  vue-tsc: "~3.0.4"

resolutionMode: highest

savePrefix: ""
