lockfileIncludeTarballUrl: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  vite: "~7.0.5"
  vue-tsc: "~3.0.3"

resolutionMode: highest

savePrefix: ""
