lockfileIncludeTarballUrl: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  vite: "npm:rolldown-vite@latest"

publicHoistPattern:
  - "nuxt-schema-org"

resolutionMode: highest

savePrefix: ""
