name: Contributors

on:
  push:
    branches:
      - master

jobs:
  contributors:
    runs-on: ubuntu-slim
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          affiliation: "all"
          commitMessage: "chore(contributors) [skip ci]"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          includeBots: true
          round: true
          sort: true
          svgPath: CONTRIBUTORS.svg
          truncate: 0
